# Periodically checks the nuget.org V3 catalog pages for changes.
# Inspired by https://simonwillison.net/2020/Oct/9/git-scraping/

name: Update data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install tool
      run: dotnet tool install --global Knapcode.CatalogCrawler --version 0.0.5-beta
    - name: Run tool
      run: Knapcode.CatalogCrawler download --data-dir . --depth CatalogPage --json-formatting PrettyWhenUnindented
    - name: Commit and push data has changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
